// Generated by gencpp from file try_ser_cli/addints.msg
// DO NOT EDIT!


#ifndef TRY_SER_CLI_MESSAGE_ADDINTS_H
#define TRY_SER_CLI_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <try_ser_cli/addintsRequest.h>
#include <try_ser_cli/addintsResponse.h>


namespace try_ser_cli
{

struct addints
{

typedef addintsRequest Request;
typedef addintsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addints
} // namespace try_ser_cli


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::try_ser_cli::addints > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::try_ser_cli::addints&) { return value(); }
};

template<>
struct DataType< ::try_ser_cli::addints > {
  static const char* value()
  {
    return "try_ser_cli/addints";
  }

  static const char* value(const ::try_ser_cli::addints&) { return value(); }
};


// service_traits::MD5Sum< ::try_ser_cli::addintsRequest> should match
// service_traits::MD5Sum< ::try_ser_cli::addints >
template<>
struct MD5Sum< ::try_ser_cli::addintsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::try_ser_cli::addints >::value();
  }
  static const char* value(const ::try_ser_cli::addintsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::try_ser_cli::addintsRequest> should match
// service_traits::DataType< ::try_ser_cli::addints >
template<>
struct DataType< ::try_ser_cli::addintsRequest>
{
  static const char* value()
  {
    return DataType< ::try_ser_cli::addints >::value();
  }
  static const char* value(const ::try_ser_cli::addintsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::try_ser_cli::addintsResponse> should match
// service_traits::MD5Sum< ::try_ser_cli::addints >
template<>
struct MD5Sum< ::try_ser_cli::addintsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::try_ser_cli::addints >::value();
  }
  static const char* value(const ::try_ser_cli::addintsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::try_ser_cli::addintsResponse> should match
// service_traits::DataType< ::try_ser_cli::addints >
template<>
struct DataType< ::try_ser_cli::addintsResponse>
{
  static const char* value()
  {
    return DataType< ::try_ser_cli::addints >::value();
  }
  static const char* value(const ::try_ser_cli::addintsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRY_SER_CLI_MESSAGE_ADDINTS_H
